#!/usr/bin/env python3
"""
Generate Niubash completion TOML from WinuxCmd help output.

The generator has three input modes:
  1. Live probing: parse `winuxcmd.exe --help` for the applet inventory, then
     each applet's `winuxcmd <applet> --help` (default; requires the exe).
  2. `--from-corpus <dir>`: replay committed `*.help` transcripts instead of
     running the exe. Used by scripts/test-winuxcmd-completions.py so the
     golden check is deterministic and CI-runnable without the binary.
  3. `--capture-corpus <dir>`: write the raw per-applet transcripts alongside
     generation, so a live run can refresh the committed corpus fixture.

Outputs:
  - One completion TOML per applet under --out-dir (one file per applet so a
    user override is a plain same-named file drop, matching the runtime's
    stem == command override rule).
  - --rust-module: a generated Rust source that embeds every TOML via
    include_str!, consumed by ExternalCompletionPlugin::new().

The generated TOML is intentionally static. Runtime completion stays reserved
for values that are truly environment-dependent.

Help text is the specification. Where the help only says `ARG`, the flag value
stays opaque (no values_from), because completing filenames as the generic
fallback is the honest default; path completion is asserted only when the
value hint names a path-ish placeholder (FILE, DIR, ...) or the flag appears
in the curated PATH_VALUE_NAMES table. STATIC_VALUES may encode GNU-spec
knowledge for flags whose WinuxCmd help wraps or omits the value list.
"""

from __future__ import annotations

import argparse
import os
import re
import shutil
import subprocess
import sys
from dataclasses import dataclass, field
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUT_DIR = ROOT / "crates" / "niubash-runtime" / "assets" / "completions" / "winuxcmd"
DEFAULT_RUST_MODULE = ROOT / "crates" / "niubash-runtime" / "src" / "completion" / "winuxcmd_assets.rs"
DEFAULT_CORPUS_DIR = ROOT / "crates" / "niubash-runtime" / "tests" / "fixtures" / "winuxcmd-help-corpus"

GENERATED_HEADER = "# Generated by scripts/generate-winuxcmd-completions.py; do not edit by hand."
RUST_MODULE_HEADER = """\
// Generated by scripts/generate-winuxcmd-completions.py; do not edit by hand.
//! Embedded WinuxCmd applet completion definitions (compiled fallback layer).
//!
//! One `include_str!` entry per `assets/completions/winuxcmd/<applet>.toml`.
//! Load order contract (see `ExternalCompletionPlugin`): these defaults are
//! seeded at construction time; bundle definitions replace them per command,
//! and user completion dirs override everything.
#[allow(clippy::module_name_repetitions)]
pub static WINUXCMD_COMPLETION_TOMLS: &[(&str, &str)] = &["""
SAFE_COMMAND_RE = re.compile(r"^[A-Za-z0-9_.+\[\]-]+$")
INVENTORY_RE = re.compile(r"^\s{2,}([A-Za-z0-9_.+\[\]-]+)\s{2,}(.+?)\s*$")
OPTION_START_RE = re.compile(r"^\s{2,}(-[A-Za-z0-9?]|--[A-Za-z0-9][A-Za-z0-9_.-]*|-\d)")
OPTION_LINE_RE = re.compile(r"^\s{2,}(.+?)(?:\s{2,}(.+))?$")
# GNU projects (gawk 5.4.1 is the first live source, niubash#189) print
# options with SINGLE-TAB indentation in the classic dual-column layout:
# "\t-f progfile\t\t--file=progfile". WinuxCmd's own help indents with 2+
# spaces and separates the description column the same way, so the tab form
# is gated on a literal leading tab everywhere below: space-only transcripts
# parse exactly as before (the golden corpus is byte-identical proof).
TAB_OPTION_START_RE = re.compile(r"^\t(-[A-Za-z0-9?]|--[A-Za-z0-9][A-Za-z0-9_.-]*|-\d)")
TAB_OPTION_LINE_RE = re.compile(r"^\t(\S.*)$")
# GNU dual-column section header ("POSIX options:\t\tGNU long options:
# (standard)"): the first tab-delimited cell is the header text. An option
# line's first cell is empty (the line starts with the tab), so it never
# qualifies.
def is_tab_section_header(line: str) -> bool:
    if "\t" not in line:
        return False
    first_cell = line.split("\t", 1)[0]
    text = first_cell.strip()
    return bool(text) and text.endswith(":")
LONG_OPTION_RE = re.compile(r"^(--[A-Za-z0-9][A-Za-z0-9_.-]*)(.*)$")
SHORT_OPTION_RE = re.compile(r"^(-[A-Za-z0-9?][A-Za-z0-9_.-]*|-\d+)(.*)$")
VALUE_HINT_RE = re.compile(r"(?:^|[\s=\[<])(ARG|ARGS|NUM|NUMBER|FILE|FILES|DIR|DIRECTORY|PATH|PATTERN|WHEN|WORD|MODE|SIZE|TYPE|NAME|COMMAND|FORMAT|STYLE|COLOR|KEY|VALUE|N)(?:\]|\>|$|\s)", re.I)
POSSIBLE_VALUES_RE = re.compile(r"\[possible values?:\s*([^\]]+)\]", re.I)
QUOTED_VALUES_RE = re.compile(r"'([A-Za-z0-9_.+-]+)'")
# Bounded inline enumeration: "how to handle directories: read, recurse, skip".
# Requires 2-6 single lowercase words after a colon; connectives are dropped.
COLON_ENUM_RE = re.compile(r":\s+([a-z0-9_-]+(?:,\s+[a-z0-9_-]+)+)\.?(?:\s|$)")
COLON_ENUM_STOPWORDS = {"or", "and", "the", "of", "e.g", "i.e"}
FOOTER_RE = re.compile(r"^WinuxCmd is a Windows implementation\b")
SECTION_END_HEADERS = {
    "exit status:",
    "examples:",
    "available commands:",
    "commands:",
    "arguments:",
    "options:",
    "flags:",
}


STATIC_VALUES: dict[tuple[str, str], list[str]] = {
    ("find", "-type"): ["f", "d", "l"],
    ("find", "-xtype"): ["f", "d", "l"],
    ("grep", "--color"): ["always", "auto", "never"],
    ("grep", "--colour"): ["always", "auto", "never"],
    ("ls", "--color"): ["always", "auto", "never"],
    ("ls", "--sort"): ["none", "size", "time", "version", "extension"],
    ("ls", "--format"): [
        "across",
        "commas",
        "horizontal",
        "long",
        "single-column",
        "verbose",
        "vertical",
    ],
    ("ls", "--time"): ["atime", "access", "use", "ctime", "status"],
    ("mv", "--interactive"): ["never", "once", "always"],
    ("rm", "--interactive"): ["never", "once", "always"],
}

PATH_VALUE_NAMES = {
    "--directory",
    "--file",
    "--files0-from",
    "--reference",
    "--target-directory",
    "--root",
    "--work-tree",
    "--git-dir",
}

# Spec value-hint placeholders that name a path-ish argument (from the help
# text itself, e.g. `-a, --arg-file FILE`, `--relative-to=DIR`).
PATH_SPEC_HINTS = {
    "file",
    "files",
    "dir",
    "directory",
    "path",
    "rfile",
    "datefile",
    "format_file",
    "file1",
    "file2",
    "manifest",
}


@dataclass
class Flag:
    short: str | None = None
    long: str | None = None
    description: str | None = None
    takes_value: bool = False
    values: list[str] = field(default_factory=list)
    values_from_path: bool = False


@dataclass
class Subcommand:
    name: str
    description: str | None = None


@dataclass
class CommandDef:
    command: str
    description: str | None = None
    flags: list[Flag] = field(default_factory=list)
    subcommands: list[Subcommand] = field(default_factory=list)


def run_capture(args: list[str], timeout: float) -> tuple[int | None, str]:
    try:
        proc = subprocess.run(
            args,
            cwd=str(ROOT),
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            timeout=timeout,
        )
        return proc.returncode, proc.stdout.replace("\r\n", "\n")
    except subprocess.TimeoutExpired as exc:
        output = ""
        if exc.stdout:
            output += exc.stdout if isinstance(exc.stdout, str) else exc.stdout.decode("utf-8", "replace")
        if exc.stderr:
            output += exc.stderr if isinstance(exc.stderr, str) else exc.stderr.decode("utf-8", "replace")
        return None, output
    except OSError as exc:
        return None, str(exc)


def locate_winuxcmd(explicit: str | None) -> Path:
    candidates: list[Path] = []
    if explicit:
        candidates.append(Path(explicit))
    if os.environ.get("WINUXCMD_PATH"):
        candidates.append(Path(os.environ["WINUXCMD_PATH"]))

    path_hit = shutil.which("winuxcmd.exe") or shutil.which("winuxcmd")
    if path_hit:
        candidates.append(Path(path_hit))

    for candidate in candidates:
        if candidate.is_dir():
            candidate = candidate / "winuxcmd.exe"
        if candidate.is_file():
            return candidate

    raise SystemExit("winuxcmd.exe not found; pass --winuxcmd or set WINUXCMD_PATH")


def discover_core_commands(winuxcmd: Path, timeout: float) -> dict[str, str]:
    _, help_text = run_capture([str(winuxcmd), "--help"], timeout)
    return parse_inventory(help_text)


def parse_inventory(help_text: str) -> dict[str, str]:
    commands: dict[str, str] = {}
    in_commands = False

    for line in help_text.splitlines():
        stripped = line.strip()
        if stripped == "Available Commands:":
            in_commands = True
            continue
        if not in_commands:
            continue
        if not stripped:
            continue
        match = INVENTORY_RE.match(line)
        if not match:
            continue
        command, summary = match.groups()
        if SAFE_COMMAND_RE.match(command):
            commands.setdefault(command, summary.strip())

    return commands


def discover_installed_commands(winuxcmd: Path) -> dict[str, str]:
    root = winuxcmd.parent
    commands: dict[str, str] = {}
    for exe in sorted(root.glob("*.exe")):
        name = exe.stem
        if name.lower() == "winuxcmd" or not SAFE_COMMAND_RE.match(name):
            continue
        commands[name] = f"{name} command installed in the WinuxCmd root"
    return commands


def command_help(
    winuxcmd: Path,
    command: str,
    timeout: float,
    installed: bool,
    help_arg: str = "--help",
) -> str:
    if installed:
        exe = winuxcmd.parent / f"{command}.exe"
        if exe.is_file():
            _, output = run_capture([str(exe), help_arg], timeout)
            return output
    _, output = run_capture([str(winuxcmd), command, help_arg], timeout)
    return output


def parse_description(help_text: str, fallback: str | None) -> str | None:
    lines = help_text.splitlines()
    desc: list[str] = []
    seen_usage = False

    for line in lines:
        stripped = line.strip()
        lower = stripped.lower()
        if lower.startswith("usage:") or lower == "usage:":
            seen_usage = True
            continue
        if not seen_usage:
            continue
        if is_option_section_header(stripped) or lower in SECTION_END_HEADERS:
            break
        if is_tab_section_header(line):
            # GNU dual-column header ("POSIX options:\tGNU long options: ...
            # (standard)"): the option table starts here; the description
            # region is over.
            break
        if FOOTER_RE.match(stripped):
            break
        if OPTION_START_RE.match(line) or TAB_OPTION_START_RE.match(line):
            # Headerless help (e.g. top 1.1.5) starts its option list directly
            # after the usage line; the description must stop there.
            break
        if not stripped:
            if desc:
                break
            continue
        if stripped.startswith("Usage:"):
            continue
        desc.append(stripped)

    description = " ".join(desc).strip()
    return description or fallback


def is_option_section_header(stripped: str) -> bool:
    lower = stripped.lower()
    return lower in {"options:", "flags:", "command options:", "global options:"} or lower.endswith(" options:")


def parse_subcommands(help_text: str) -> list[Subcommand]:
    """Parse a `Commands:` section into subcommand definitions.

    Handles the wpm-style inventory where the left column mixes bare names
    with usage hints: `uninstall|remove|erase <package>...`,
    `cache clean [cache|staging|all]`, `index status|update`. The name column
    is separated from the description by a 2+ space gap; a usage hint after a
    single space belongs to the name column and is ignored for completion.
    """
    subcommands: list[Subcommand] = []
    seen: set[str] = set()
    in_commands = False

    for line in help_text.splitlines():
        stripped = line.strip()
        if stripped.lower() == "commands:":
            in_commands = True
            continue
        if not in_commands:
            continue
        if not stripped:
            continue
        lower = stripped.lower()
        if is_option_section_header(stripped) or lower in SECTION_END_HEADERS:
            break
        match = re.match(r"^\s{2,}(\S+)(?:\s+\S.*?)?\s{2,}(\S.*?)\s*$", line)
        if not match:
            continue
        name_column, summary = match.groups()
        for name in name_column.split("|"):
            if name and SAFE_COMMAND_RE.match(name) and name not in seen:
                seen.add(name)
                subcommands.append(Subcommand(name=name, description=summary.strip() or None))

    return subcommands


def canonicalize_gnu_spec(spec: str) -> str:
    """Canonicalize a GNU dual-column spec to WinuxCmd comma style.

    "\t-f progfile\t\t--file=progfile" becomes "-f progfile, --file=progfile"
    so parse_flag_spec sees the same "-x, --long" shape as native WinuxCmd
    help. Cells before the first long option are the short option plus its
    value hint (joined with single spaces); every long option cell is joined
    with ", ". Space-only specs never reach this function (tab-gated), so
    native transcripts are untouched.
    """
    cells = [cell for cell in (part.strip() for part in re.split(r"\t+|\s{2,}", spec)) if cell]
    head: list[str] = []
    longs: list[str] = []
    for cell in cells:
        if cell.startswith("--"):
            longs.append(cell)
        elif not longs:
            head.append(cell)
    pieces = []
    if head:
        pieces.append(" ".join(head))
    pieces.extend(longs)
    return ", ".join(pieces)


def parse_flags(command: str, help_text: str) -> list[Flag]:
    lines = help_text.splitlines()
    if any(is_option_section_header(line.strip()) for line in lines):
        blocks = _scan_option_blocks(lines, start_in_options=False)
    else:
        # Some applets (e.g. top 1.1.5) list options directly after the usage
        # line with no `Options:` header. Scan the whole transcript; usage
        # lines never start with a flag token and the footer/section-end
        # guards still apply.
        blocks = _scan_option_blocks(lines, start_in_options=True)

    flags: list[Flag] = []
    seen: set[tuple[str | None, str | None]] = set()
    for spec, description in blocks:
        flag = parse_flag_spec(command, spec, description)
        if flag is None:
            continue
        key = (flag.short, flag.long)
        if key in seen:
            continue
        seen.add(key)
        flags.append(flag)
    return flags


def _scan_option_blocks(
    lines: list[str],
    start_in_options: bool,
) -> list[tuple[str, str]]:
    blocks: list[tuple[str, str]] = []
    in_options = start_in_options
    current_spec: str | None = None
    current_desc: list[str] = []
    seen_option = False

    for line in lines:
        stripped = line.strip()
        if is_option_section_header(stripped):
            in_options = True
            flush_block(blocks, current_spec, current_desc)
            current_spec = None
            current_desc = []
            continue
        if not in_options:
            continue
        if not stripped:
            continue
        # Section-end headers must win over the fzf-style subgroup continue
        # below, otherwise "EXIT STATUS:" is swallowed as a subgroup and its
        # body (plus the trailing WinuxCmd footer) pollutes the last flag's
        # description.
        if stripped.lower() in SECTION_END_HEADERS:
            break
        if FOOTER_RE.match(stripped):
            break
        # GNU dual-column section headers sit flush-left ("POSIX options:\t
        # GNU long options: (standard)"), so the tab-header check must run
        # BEFORE the flush-left prose pause below: a header continues the
        # scan into the next table, prose merely pauses it.
        if is_tab_section_header(line):
            flush_block(blocks, current_spec, current_desc)
            current_spec = None
            current_desc = []
            continue
        # Flush-left non-header line: GNU help interleaves such prose with
        # option tables two ways — mid-help interludes (echo 1.1.5: "`echo`
        # interprets the following backslash-escaped characters:" followed by
        # MORE options) and terminal notices (gawk 5.4.1: the GPL block).
        # Either way the current flag's description is over: flush the block
        # and PAUSE the table (drop continuation lines) but keep scanning, so
        # later options still parse and prose never glues onto a flag.
        if seen_option and line and not line[0].isspace():
            flush_block(blocks, current_spec, current_desc)
            current_spec = None
            current_desc = []
            continue
        if stripped.endswith(":") and not OPTION_START_RE.match(line):
            # fzf-style subgroups inside the options section; keep parsing.
            continue

        tab_line = TAB_OPTION_START_RE.match(line)
        space_line = OPTION_START_RE.match(line)
        if space_line or tab_line:
            flush_block(blocks, current_spec, current_desc)
            if tab_line:
                # GNU dual-column layout: the whole tab-led remainder is the
                # spec column (short option, value hint, long alias); there
                # is no description column.
                current_spec = canonicalize_gnu_spec(
                    TAB_OPTION_LINE_RE.match(line).group(1)
                )
                current_desc = []
            else:
                match = OPTION_LINE_RE.match(line)
                if not match:
                    current_spec = None
                    current_desc = []
                    continue
                current_spec = match.group(1).strip()
                current_desc = [match.group(2).strip()] if match.group(2) else []
            seen_option = True
        elif current_spec is not None:
            current_desc.append(stripped)

    flush_block(blocks, current_spec, current_desc)
    return blocks


def flush_block(blocks: list[tuple[str, str]], spec: str | None, desc: list[str]) -> None:
    if not spec:
        return
    description = " ".join(part.strip() for part in desc if part.strip()).strip()
    blocks.append((spec, description))


def parse_flag_spec(command: str, spec: str, description: str) -> Flag | None:
    pieces = [piece.strip() for piece in spec.split(",")]
    short: str | None = None
    long: str | None = None
    takes_value = False
    hint_tokens: list[str] = []

    for piece in pieces:
        if not piece:
            continue
        parsed, trailing, kind = normalize_option(piece)
        if parsed is None:
            continue
        # First alias wins: a spec like `-F, -f` (pr) must not lose its first
        # short to the second one.
        if kind == "long" and long is None:
            long = parsed
        elif kind == "short" and short is None:
            short = parsed
        optional, hint = split_value_hint(piece, trailing)
        if hint:
            hint_tokens.append(hint)
        if optional:
            # `[=ARG]` marks an optional argument: the bare flag is completed
            # as a plain flag (the GNU form requires `=` to pass the value),
            # so it must not swallow filename completion after a space.
            pass
        elif hint and looks_value_hint(hint):
            takes_value = True
        elif "=" in piece:
            takes_value = True

    if short is None and long is None:
        return None

    flag = Flag(short=short, long=long, description=description or None, takes_value=takes_value)
    assign_value_source(command, flag, hint_tokens)
    return flag


def split_value_hint(piece: str, trailing: str) -> tuple[bool, str]:
    """Return (value_is_optional, hint_token) for one spec piece."""
    bracket = re.search(r"\[=([^\]]*)\]", piece)
    if bracket:
        return True, bracket.group(1).strip()
    plain = re.search(r"[= ]([A-Za-z][A-Za-z0-9_.<>-]*)\s*$", trailing or "")
    if plain:
        return False, plain.group(1).strip("<>")
    trailing = (trailing or "").strip()
    if trailing:
        return False, trailing.strip("<>")
    return False, ""


def normalize_option(piece: str) -> tuple[str | None, str, str | None]:
    piece = piece.strip()
    if piece.startswith("+"):
        return None, "", None

    long_match = LONG_OPTION_RE.match(piece)
    if long_match:
        option = long_match.group(1)
        if option.endswith("..."):
            option = option[:-3]
        trailing = long_match.group(2).strip()
        return option, trailing, "long"

    short_match = SHORT_OPTION_RE.match(piece)
    if short_match:
        option = short_match.group(1)
        trailing = short_match.group(2).strip()
        return option, trailing, "short"

    return None, "", None


def looks_value_hint(trailing: str) -> bool:
    return bool(
        VALUE_HINT_RE.search(trailing)
        or re.search(r"<[^>]+>", trailing)
        or re.search(r"\[[A-Z0-9_ -]+\]", trailing)
    )


def assign_value_source(command: str, flag: Flag, hint_tokens: list[str]) -> None:
    if not flag.takes_value:
        return

    for name in [flag.long, flag.short]:
        if name and (command, name) in STATIC_VALUES:
            flag.values = STATIC_VALUES[(command, name)]
            return

    possible = extract_possible_values(flag.description or "")
    if possible:
        flag.values = possible
        return

    names = [name for name in [flag.long, flag.short] if name]
    hint_is_path = any(token.lower() in PATH_SPEC_HINTS for token in hint_tokens)
    if any(name in PATH_VALUE_NAMES for name in names) or hint_is_path:
        flag.values_from_path = True


def extract_possible_values(description: str) -> list[str]:
    match = POSSIBLE_VALUES_RE.search(description)
    if match:
        raw = match.group(1)
        values = [part.strip(" `,.;") for part in re.split(r"[,|]", raw)]
        return [value for value in values if value and " " not in value]

    colon = COLON_ENUM_RE.search(description)
    if colon:
        candidates = [part.strip(" .") for part in colon.group(1).split(",")]
        values = [part for part in candidates if part and part not in COLON_ENUM_STOPWORDS]
        if 2 <= len(values) <= 6 and all(re.fullmatch(r"[a-z0-9_-]+", value) for value in values):
            return values

    quoted = QUOTED_VALUES_RE.findall(description)
    if 2 <= len(quoted) <= 8:
        return quoted

    return []


def toml_escape(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


def render_command(defn: CommandDef) -> str:
    lines = [GENERATED_HEADER, f'command = "{toml_escape(defn.command)}"']
    if defn.description:
        lines.append(f'description = "{toml_escape(defn.description)}"')

    for flag in defn.flags:
        lines.append("")
        lines.append("[[flags]]")
        if flag.short:
            lines.append(f'short = "{toml_escape(flag.short)}"')
        if flag.long:
            lines.append(f'long = "{toml_escape(flag.long)}"')
        if flag.description:
            lines.append(f'description = "{toml_escape(flag.description)}"')
        if flag.takes_value:
            lines.append("takes_value = true")
        if flag.values:
            rendered = ", ".join(f'"{toml_escape(value)}"' for value in flag.values)
            lines.append(f"values = [{rendered}]")
        elif flag.values_from_path:
            lines.append('values_from = "path"')

    for subcommand in defn.subcommands:
        lines.append("")
        lines.append("[[subcommands]]")
        lines.append(f'name = "{toml_escape(subcommand.name)}"')
        if subcommand.description:
            lines.append(f'description = "{toml_escape(subcommand.description)}"')

    lines.append("")
    return "\n".join(lines)


def generated_filename(command: str) -> str:
    # Keep `[` literal so the file stem equals the command name (the runtime's
    # user-override rule matches on stem == command).
    safe = re.sub(r"[^A-Za-z0-9_.+\[\]-]+", "_", command).strip("._")
    return f"{safe or 'command'}.toml"


def render_rust_module(defs: list[CommandDef]) -> str:
    # Entry layout must stay rustfmt-stable (no blank lines between entries):
    # cargo fmt runs as a pre-commit hook and the golden check diffs this file
    # byte-for-byte against the generator output.
    lines = [RUST_MODULE_HEADER]
    for defn in defs:
        filename = generated_filename(defn.command)
        lines.append("    (")
        lines.append(f'        "{toml_escape(defn.command)}",')
        lines.append(f'        include_str!("../../assets/completions/winuxcmd/{filename}"),')
        lines.append("    ),")
    lines.append("];")
    lines.append("")
    lines.append(
        "/// Parse every embedded definition. Files that fail to parse are\n"
        "/// skipped with a warning; a broken asset is a build/CI problem (the\n"
        "/// golden test regenerates and diffs these files), not a runtime one."
    )
    lines.append(
        "pub fn definitions() -> impl Iterator<Item = crate::completion::external::CommandDef> {"
    )
    lines.append("    WINUXCMD_COMPLETION_TOMLS")
    lines.append("        .iter()")
    lines.append("        .filter_map(|(command, toml)| match toml::from_str(toml) {")
    lines.append("            Ok(def) => Some(def),")
    lines.append('            Err(e) => {')
    lines.append(
        '                log::warn!("embedded winuxcmd completion {command} failed to parse: {e}");'
    )
    lines.append("                None")
    lines.append("            }")
    lines.append("        })")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--winuxcmd", help="Path to winuxcmd.exe or its containing directory")
    parser.add_argument("--out-dir", type=Path, default=DEFAULT_OUT_DIR)
    parser.add_argument("--rust-module", type=Path, default=DEFAULT_RUST_MODULE)
    parser.add_argument(
        "--from-corpus",
        type=Path,
        help="Replay committed *.help transcripts from this dir instead of running winuxcmd.exe",
    )
    parser.add_argument(
        "--capture-corpus",
        type=Path,
        help="Additionally write each applet's raw --help transcript to this dir",
    )
    parser.add_argument("--timeout", type=float, default=2.5)
    parser.add_argument(
        "--include-installed",
        action="store_true",
        help="Also parse installed .exe tools in the WinuxCmd root, including WPM packages",
    )
    parser.add_argument(
        "--commands",
        help="Comma-separated command allowlist; useful for focused regeneration",
    )
    args = parser.parse_args()

    if args.from_corpus:
        corpus_dir = args.from_corpus
        if not corpus_dir.is_dir():
            raise SystemExit(f"corpus dir not found: {corpus_dir}")
        transcripts = {
            path.stem: path.read_text(encoding="utf-8")
            for path in sorted(corpus_dir.glob("*.help"))
            if path.stem != "winuxcmd"
        }
        # `winuxcmd.help` is the multi-call binary's own --help transcript; it
        # supplies the one-line inventory summaries used as description
        # fallbacks, so replay is byte-identical to a live run.
        inventory_text = corpus_dir.joinpath("winuxcmd.help")
        inventory = parse_inventory(inventory_text.read_text(encoding="utf-8")) if inventory_text.is_file() else {}
        commands = {name: inventory.get(name) for name in transcripts}
    else:
        winuxcmd = locate_winuxcmd(args.winuxcmd)
        _, inventory_text = run_capture([str(winuxcmd), "--help"], args.timeout)
        commands = parse_inventory(inventory_text)
        transcripts = {}
        installed_commands: set[str] = set()

        if args.include_installed:
            installed = discover_installed_commands(winuxcmd)
            installed_commands = set(installed) - set(commands)
            commands.update(installed)

        if args.capture_corpus:
            args.capture_corpus.mkdir(parents=True, exist_ok=True)
            (args.capture_corpus / "winuxcmd.help").write_text(
                inventory_text,
                encoding="utf-8",
                newline="\n",
            )

        for command in commands:
            help_text = command_help(
                winuxcmd,
                command,
                args.timeout,
                installed=command in installed_commands,
            )
            if not help_text.strip():
                help_text = command_help(
                    winuxcmd,
                    command,
                    args.timeout,
                    installed=command in installed_commands,
                    help_arg="-h",
                )
            transcripts[command] = help_text
            if args.capture_corpus:
                (args.capture_corpus / generated_filename(command).replace(".toml", ".help")).write_text(
                    help_text,
                    encoding="utf-8",
                    newline="\n",
                )

    if args.commands:
        allowed = {item.strip() for item in args.commands.split(",") if item.strip()}
        commands = {name: summary for name, summary in commands.items() if name in allowed}

    if not commands:
        raise SystemExit("no commands discovered")

    args.out_dir.mkdir(parents=True, exist_ok=True)

    generated = 0
    skipped = 0
    generated_defs: list[CommandDef] = []
    for command, fallback in sorted(commands.items()):
        help_text = transcripts.get(command, "")
        flags = parse_flags(command, help_text)
        subcommands = parse_subcommands(help_text)
        if not flags and not help_text.strip():
            skipped += 1
            continue
        defn = CommandDef(
            command=command,
            description=parse_description(help_text, fallback),
            flags=flags,
            subcommands=subcommands,
        )
        (args.out_dir / generated_filename(command)).write_text(
            render_command(defn),
            encoding="utf-8",
            newline="\n",
        )
        generated_defs.append(defn)
        generated += 1

    generated_defs.sort(key=lambda d: d.command)
    args.rust_module.parent.mkdir(parents=True, exist_ok=True)
    args.rust_module.write_text(render_rust_module(generated_defs), encoding="utf-8", newline="\n")

    print(
        f"generated {generated} completion definitions into {args.out_dir} "
        f"(module {args.rust_module}); skipped {skipped}"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
