#!/usr/bin/env python3
"""Generate the data-driven regions of the niubash agent skill bundle.

Hand-written command lists rot (the same lesson as the WinuxCmd completion
assets, wt75/#172). This generator owns every command table in
`skills/niubash/`: the regions between

    <!-- BEGIN GENERATED:<key> -->
    <!-- END GENERATED:<key> -->

in a template are replaced on every run; everything outside the markers is
hand-curated prose.

Sources of truth
----------------
1. Shell builtin table — the rubash engine's GNU bash 5.3 `shell_builtins[]`
   help table, captured through the shipping surface:
       <niu> -c 'help -s "*"'
   Committed transcript: crates/niubash-runtime/tests/fixtures/skill-corpus/
   builtin-short-help.txt.
2. Launcher + plugin verb surface — `niu --help`, with the leading version
   line normalized to `Niubash <version>` so the corpus does not churn on
   every release. Committed transcript: .../skill-corpus/niu-help.txt.
3. WinuxCmd applet inventory — one completion TOML per applet under
   crates/niubash-runtime/assets/completions/winxcmd/ (generated by
   scripts/generate-winuxcmd-completions.py from that corpus).
4. Bundle version — [package] version in Cargo.toml.

Modes
-----
    python scripts/generate-skill.py                        # replay corpus, rewrite in place
    python scripts/generate-skill.py --check                # golden: nonzero exit on drift, no writes
    python scripts/generate-skill.py --capture --niu <exe>  # refresh corpus from a live build, rewrite

`--check` is the golden gate (scripts/test-skill-bundle.py wraps it and also
byte-compares a temp rewrite, mirroring scripts/test-winuxcmd-completions.py).
Drift means either the corpus is stale relative to a product change or a
generated region was hand-edited — both are resolved by re-running this
script (with `--capture` after a `niu --help`/`help -s` change).
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CORPUS_DIR = ROOT / "crates" / "niubash-runtime" / "tests" / "fixtures" / "skill-corpus"
APPLET_DIR = ROOT / "crates" / "niubash-runtime" / "assets" / "completions" / "winuxcmd"
CARGO_TOML = ROOT / "Cargo.toml"
TEMPLATES = [
    ROOT / "skills" / "niubash" / "SKILL.md",
    ROOT / "skills" / "niubash" / "references" / "quickref.md",
]

BEGIN_RE = re.compile(r"<!-- BEGIN GENERATED:(?P<key>[a-z0-9-]+) -->")
END_RE = re.compile(r"<!-- END GENERATED:(?P<key>[a-z0-9-]+) -->")

# `help -s "*"` prints a keyword header line, then `name: synopsis` rows.
BUILTIN_ROW_RE = re.compile(r"^(?P<name>.+?): (?P<synopsis>.*)$")

# `niu --help` verb rows: 2+ spaces between the verb shape and its description.
VERB_ROW_RE = re.compile(r"^(?P<verb>\S.*?)\s{2,}(?P<desc>\S.*)$")


def bundle_version() -> str:
    for line in CARGO_TOML.read_text(encoding="utf-8").splitlines():
        match = re.match(r'^version\s*=\s*"([^"]+)"', line)
        if match:
            return match.group(1)
    raise SystemExit(f"FAIL generate-skill: no [package] version in {CARGO_TOML}")


def read_corpus() -> tuple[list[tuple[str, str]], list[str], list[tuple[str, str]]]:
    """Return (builtin rows, applet names, plugin verb rows)."""
    builtin_lines = (CORPUS_DIR / "builtin-short-help.txt").read_text(
        encoding="utf-8"
    ).splitlines()
    builtins: list[tuple[str, str]] = []
    for line in builtin_lines:
        if not line.strip() or line.startswith("Shell commands matching"):
            continue
        match = BUILTIN_ROW_RE.match(line)
        if not match:
            raise SystemExit(f"FAIL generate-skill: unparsable builtin row: {line!r}")
        builtins.append((match.group("name"), match.group("synopsis")))

    niu_help = (CORPUS_DIR / "niu-help.txt").read_text(encoding="utf-8").splitlines()

    applets = sorted(
        path.stem for path in APPLET_DIR.glob("*.toml") if path.is_file()
    )
    if not applets:
        raise SystemExit(
            f"FAIL generate-skill: no applet completion TOMLs under {APPLET_DIR}"
        )
    return builtins, applets, niu_help


def extract_help_block(lines: list[str], start_re: re.Pattern[str]) -> list[str]:
    """Return the contiguous block of non-blank lines starting at `start_re`."""
    block: list[str] = []
    started = False
    for line in lines:
        if started:
            if not line.strip():
                break
            block.append(line)
        elif start_re.match(line):
            started = True
            block.append(line)
    if not block:
        raise SystemExit(f"FAIL generate-skill: block {start_re.pattern!r} not found")
    return block


def render_builtin_names(builtins: list[tuple[str, str]]) -> str:
    """One wrapped paragraph of builtin names for the SKILL.md body."""
    names = [f"`{name}`" for name, _ in builtins]
    lines: list[str] = []
    current: list[str] = []
    width = 0
    for name in names:
        if current and width + 1 + len(name) > 92:
            lines.append(" ".join(current) + "  ")
            current, width = [], 0
        current.append(name)
        width += len(name) + (1 if width else 0)
    if current:
        lines.append(" ".join(current) + "  ")
    return "\n".join(line.rstrip() for line in lines).rstrip()


def render_builtin_table(builtins: list[tuple[str, str]]) -> str:
    escaped = (
        (name, synopsis.replace("|", "\\|")) for name, synopsis in builtins
    )
    rows = ["| Command | Synopsis |", "| --- | --- |"]
    rows += [f"| `{name}` | {synopsis} |" for name, synopsis in escaped]
    return "\n".join(rows)


def render_applets(applets: list[str]) -> str:
    """Count + wrapped applet list, markdown-safe inside a fenced block."""
    lines: list[str] = []
    current: list[str] = []
    width = 0
    for name in applets:
        if current and width + 1 + len(name) > 88:
            lines.append(" ".join(current))
            current, width = [], 0
        current.append(name)
        width += len(name) + (1 if width else 0)
    if current:
        lines.append(" ".join(current))
    return "\n".join(lines)


def render_launcher_verbs(niu_help: list[str]) -> str:
    """The verb rows of `niu --help`: usage block + REPL verbs, verbatim."""
    usage = extract_help_block(niu_help, re.compile(r"^Usage:\s"))
    repl = extract_help_block(niu_help, re.compile(r"^  (self-update|update-niubash)\b"))
    return "\n".join(usage + [""] + repl)


def render_plugin_verbs(niu_help: list[str]) -> str:
    """The `plugin ...` verb block of `niu --help`, verbatim."""
    return "\n".join(extract_help_block(niu_help, re.compile(r"^  plugin\s")))


def render_region(key: str, builtins: list[tuple[str, str]], applets: list[str],
                  niu_help: list[str]) -> str:
    version = bundle_version()
    if key == "capability-snapshot":
        return "\n".join([
            f"- **{len(builtins)} shell built-ins & reserved words** — the GNU "
            "bash 5.3 `shell_builtins[]` table (`alias`, `cd`, `declare`, "
            "`printf`, `set`, `trap`, `if`/`while`/`case`, ...); every one "
            "documents itself via `help <name>`.",
            f"- **{len(applets)} winuxcmd applets** on PATH (`ls`, `grep`, `sed`, "
            "`awk`, `find`, `tar`, `top`, `xxd`, ...) — real Windows binaries, "
            "not emulated inside the shell; full inventory in "
            "`references/quickref.md`.",
            "- **Launcher verbs** — `setup`, `font`, `doctor`, `plugin`, `skill`, "
            "`--self-update`; table in `references/quickref.md`.",
            "- **Plugin system** — git-clone-only external sources (oh-my-bash, "
            "bash-it, bpkg) behind an explicit trust gate, driven by a "
            "declarative spec (`~/.niubash/plugins.toml`) with lockfile verbs "
            "(`add/list/enable/disable/trust/sync/update/restore/rollback/"
            "clean/source/recipe/distro/mirror/ui`).",
            "- **TUI surfaces** — `niu setup` wizard (theme/prompt/tools), "
            "`niu plugin ui` menu, theme gallery, `niu font` picker; all "
            "non-interactive-friendly and safe to skip (`-c` loads none of "
            "them).",
            f"- **Bundle version**: niubash {version} (generated; see "
            "`scripts/generate-skill.py`).",
        ])
    if key == "builtin-names":
        return render_builtin_names(builtins)
    if key == "launcher-verbs":
        return render_launcher_verbs(niu_help)
    if key == "plugin-verbs":
        return render_plugin_verbs(niu_help)
    if key == "builtin-table":
        return render_builtin_table(builtins)
    if key == "applets":
        return render_applets(applets)
    raise SystemExit(f"FAIL generate-skill: unknown generated region key {key!r}")


def regenerate(template: str, builtins: list[tuple[str, str]], applets: list[str],
               niu_help: list[str]) -> str:
    out: list[str] = []
    lines = template.splitlines(keepends=True)
    index = 0
    replaced: set[str] = set()
    while index < len(lines):
        line = lines[index]
        begin = BEGIN_RE.match(line.strip())
        if not begin:
            out.append(line)
            index += 1
            continue
        key = begin.group("key")
        if key in replaced:
            raise SystemExit(f"FAIL generate-skill: duplicate region {key!r}")
        # Find the matching END marker.
        end_index = None
        for scan in range(index + 1, len(lines)):
            end = END_RE.match(lines[scan].strip())
            if end and end.group("key") == key:
                end_index = scan
                break
        if end_index is None:
            raise SystemExit(f"FAIL generate-skill: unterminated region {key!r}")
        out.append(f"<!-- BEGIN GENERATED:{key} -->\n")
        body = render_region(key, builtins, applets, niu_help)
        out.append(body + "\n")
        out.append(f"<!-- END GENERATED:{key} -->\n")
        replaced.add(key)
        index = end_index + 1
    missing = set(
        match.group("key")
        for template_text in [template]
        for match in BEGIN_RE.finditer(template_text)
    ) - replaced
    if missing:
        raise SystemExit(f"FAIL generate-skill: regions not rewritten: {missing}")
    return "".join(out)


def collect_corpus_from_niu(niu: Path) -> None:
    """Refresh the committed transcripts from a live niu build."""
    help_text = subprocess.run(
        [str(niu), "--help"], capture_output=True, text=True, check=True
    ).stdout
    help_text = re.sub(
        r"^Niubash \d+\.\d+\.\d+ —", "Niubash <version> —", help_text, count=1
    )
    (CORPUS_DIR / "niu-help.txt").write_text(help_text, encoding="utf-8", newline="\n")
    builtin_text = subprocess.run(
        [str(niu), "-c", 'help -s "*"'], capture_output=True, text=True, check=True
    ).stdout
    (CORPUS_DIR / "builtin-short-help.txt").write_text(
        builtin_text, encoding="utf-8", newline="\n"
    )
    print(f"captured corpus from {niu} into {CORPUS_DIR}")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true",
                        help="verify committed files match generation; no writes")
    parser.add_argument("--capture", action="store_true",
                        help="refresh the corpus transcripts from a live niu")
    parser.add_argument("--niu", type=Path, default=None,
                        help="path to a niu binary (required with --capture)")
    args = parser.parse_args()

    if args.capture:
        if args.niu is None:
            parser.error("--capture requires --niu <path-to-niu>")
        collect_corpus_from_niu(args.niu)

    builtins, applets, niu_help = read_corpus()

    if args.check:
        drift = False
        for template_path in TEMPLATES:
            regenerated = regenerate(
                template_path.read_text(encoding="utf-8"), builtins, applets, niu_help
            )
            if regenerated != template_path.read_text(encoding="utf-8"):
                print(f"DRIFT {template_path.relative_to(ROOT)}")
                drift = True
        if drift:
            print(
                "FAIL skill-bundle: generated regions drifted — run "
                "`python scripts/generate-skill.py` and commit"
            )
            return 1
        print("PASS skill-bundle")
        return 0

    with tempfile.TemporaryDirectory(prefix="niu-skill-gen-") as tmp:
        staging = Path(tmp)
        rewritten: list[tuple[Path, str]] = []
        for template_path in TEMPLATES:
            regenerated = regenerate(
                template_path.read_text(encoding="utf-8"), builtins, applets, niu_help
            )
            staged = staging / template_path.name
            staged.write_text(regenerated, encoding="utf-8", newline="\n")
            rewritten.append((template_path, staged.read_text(encoding="utf-8")))
        for template_path, content in rewritten:
            template_path.write_text(content, encoding="utf-8", newline="\n")
            print(f"rewrote {template_path.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
