//! `niu skill` — the AI agent skill bundle verbs (niubash#188).
//!
//! `skills/niubash/` at the repo root is the source of truth; the files are
//! embedded here via include_str! so the shipping `niu.exe` can install the
//! bundle anywhere without an install tree beside it. The data-driven
//! regions inside those files are generated by scripts/generate-skill.py
//! (golden-checked by scripts/test-skill-bundle.py); this module only ships
//! and installs them.
//!
//! Verbs:
//! - `niu skill install [--target claude|zcode|cursor|all|<dir>]` — write the
//!   bundle into agent skill dirs (default: claude).
//! - `niu skill status [--target ...]` — installed/outdated per target,
//!   decided by per-file content comparison, with a sha256 bundle digest.

use niubash_runtime::skill::{self, SkillFile, TargetSpec};

/// The embedded bundle: keep in sync with `skills/niubash/` (the golden
/// test scripts/test-skill-bundle.py fails when the tree and this table
/// disagree).
pub static SKILL_FILES: &[SkillFile] = &[
    SkillFile {
        rel: "SKILL.md",
        content: include_str!("../skills/niubash/SKILL.md"),
    },
    SkillFile {
        rel: "agents/openai.yaml",
        content: include_str!("../skills/niubash/agents/openai.yaml"),
    },
    SkillFile {
        rel: "references/paths.md",
        content: include_str!("../skills/niubash/references/paths.md"),
    },
    SkillFile {
        rel: "references/prompt-plugins.md",
        content: include_str!("../skills/niubash/references/prompt-plugins.md"),
    },
    SkillFile {
        rel: "references/quickref.md",
        content: include_str!("../skills/niubash/references/quickref.md"),
    },
    SkillFile {
        rel: "references/wpm.md",
        content: include_str!("../skills/niubash/references/wpm.md"),
    },
];

/// `niu skill <verb>` dispatch.
pub fn run_skill_command(args: &[String]) -> anyhow::Result<()> {
    let Some(verb) = args.get(2) else {
        print_skill_usage();
        return Ok(());
    };
    match verb.as_str() {
        "-h" | "--help" | "help" => {
            print_skill_usage();
            Ok(())
        }
        "install" => run_skill_install(&args[3..]),
        "status" => run_skill_status(&args[3..]),
        unknown => {
            print_skill_usage();
            anyhow::bail!("unknown skill verb '{}'", unknown)
        }
    }
}

fn print_skill_usage() {
    println!(
        "Usage:  niu skill install [--target {}|all|<dir>]",
        skill::named_list()
    );
    println!("        Install the AI agent skill bundle (SKILL.md + references)");
    println!("        into agent skill dirs. Default target: claude.");
    println!("        <dir> is a skills root; the bundle lands in <dir>/niubash/.");
    println!("        Same structure as the released niubash-skill-v*.zip.");
    println!("Usage:  niu skill status [--target ...]");
    println!("        Show installed/outdated state per target (content compared");
    println!("        against this binary's embedded bundle; sha256 digest printed).");
}

fn resolve_targets(args: &[String]) -> anyhow::Result<Vec<(String, std::path::PathBuf)>> {
    let mut target_spec: Option<&str> = None;
    let mut iter = args.iter();
    while let Some(arg) = iter.next() {
        if arg == "--target" {
            target_spec = Some(
                iter.next()
                    .ok_or_else(|| anyhow::anyhow!("--target requires a value"))?,
            );
        } else if let Some(value) = arg.strip_prefix("--target=") {
            target_spec = Some(value);
        } else {
            anyhow::bail!("unknown skill argument '{arg}'");
        }
    }

    let mut targets = Vec::new();
    match target_spec {
        None => {
            if let Some(dir) = skill::named_target_dir("claude") {
                targets.push(("claude".to_string(), dir));
            }
        }
        Some(spec) => match skill::resolve_target(spec)? {
            TargetSpec::Named(name) => {
                if let Some(dir) = skill::named_target_dir(name) {
                    targets.push((name.to_string(), dir));
                }
            }
            TargetSpec::All => {
                for (name, _) in skill::NAMED_TARGETS {
                    if let Some(dir) = skill::named_target_dir(name) {
                        targets.push(((*name).to_string(), dir));
                    }
                }
            }
            TargetSpec::Dir(dir) => {
                targets.push((dir.display().to_string(), dir.join(skill::SKILL_DIR_NAME)))
            }
        },
    }
    if targets.is_empty() {
        anyhow::bail!("cannot resolve the home directory for any skill target");
    }
    Ok(targets)
}

fn run_skill_install(args: &[String]) -> anyhow::Result<()> {
    let targets = resolve_targets(args)?;
    for (name, dir) in &targets {
        let written = skill::install_files(SKILL_FILES, dir)?;
        println!(
            "installed {} file(s) into {} (target: {name})",
            written,
            display(dir)
        );
    }
    Ok(())
}

fn run_skill_status(args: &[String]) -> anyhow::Result<()> {
    let targets = resolve_targets(args)?;
    let digest = skill::skill_digest(SKILL_FILES).unwrap_or_default();
    println!("bundle: niubash skill, sha256 {digest}");
    for (name, dir) in &targets {
        let status = skill::check_target(SKILL_FILES, dir);
        let state = if status.up_to_date {
            "current".to_string()
        } else if status.installed {
            format!("outdated (differing: {})", status.differing.join(", "))
        } else {
            "not installed".to_string()
        };
        println!("  {name}: {state} — {}", display(dir));
    }
    println!("install or refresh with: niu skill install");
    Ok(())
}

fn display(path: &std::path::Path) -> String {
    path.to_string_lossy().replace('\\', "/")
}
